import type { ManifestPreset } from '../types/scanner';

export const MANIFEST_PRESETS: ManifestPreset[] = [
  {
    id: 'llm-hallucinated-nextjs',
    name: 'LLM-Hallucinated Next.js Fullstack Manifest',
    ecosystem: 'npm',
    filename: 'package.json',
    description: 'Generated by an LLM assistant suggesting plausible but completely non-existent npm helper packages.',
    blastRadius: 92,
    rawContent: `{
  "name": "enterprise-customer-portal",
  "version": "1.0.0",
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "@next-auth/secure-cookies": "^1.0.4",
    "tailwind-color-extractor": "^0.8.1",
    "react-dom-telemetry": "^2.1.0",
    "lucide-react": "^0.395.0",
    "zod": "^3.23.8"
  }
}`,
    dependencies: [
      {
        id: 'dep-1',
        name: '@next-auth/secure-cookies',
        version: '^1.0.4',
        ecosystem: 'npm',
        riskLevel: 'CRITICAL',
        anomalyType: 'HALLUCINATED',
        registryExists: false,
        hallucinationProbability: 98,
        weeklyDownloads: '0',
        age: 'UNREGISTERED',
        reason: 'Phantom Package (LLM Hallucination)',
        threatDetails: 'Package does not exist on npm. Anyone can register this package right now and execute arbitrary postinstall scripts across all developer workstations and CI runners.',
        suggestedAction: 'Claim name immediately on npm registry to prevent attacker squatting.',
        claimCommand: 'npx npm-claim @next-auth/secure-cookies'
      },
      {
        id: 'dep-2',
        name: 'tailwind-color-extractor',
        version: '^0.8.1',
        ecosystem: 'npm',
        riskLevel: 'CRITICAL',
        anomalyType: 'HALLUCINATED',
        registryExists: false,
        hallucinationProbability: 95,
        weeklyDownloads: '0',
        age: 'UNREGISTERED',
        reason: 'Phantom Package (AI Hallucination)',
        threatDetails: 'Synthesized dependency suggested during prompt code generation. Zero registry presence.',
        suggestedAction: 'Replace with native tailwindcss/colors module.',
        claimCommand: 'npx npm-claim tailwind-color-extractor'
      },
      {
        id: 'dep-3',
        name: 'react-dom-telemetry',
        version: '^2.1.0',
        ecosystem: 'npm',
        riskLevel: 'HIGH',
        anomalyType: 'TYPOSQUAT',
        registryExists: true,
        hallucinationProbability: 84,
        weeklyDownloads: '14',
        age: '2 days ago',
        reason: 'Typosquat / Suspicious Fresh Release',
        threatDetails: 'Uploaded 48 hours ago with zero source repository and single suspicious maintainer account.',
        suggestedAction: 'Remove and report to npm security team.',
        claimCommand: 'npm unpublish react-dom-telemetry --force'
      },
      {
        id: 'dep-4',
        name: 'next',
        version: '^14.2.0',
        ecosystem: 'npm',
        riskLevel: 'SAFE',
        anomalyType: 'VERIFIED',
        registryExists: true,
        hallucinationProbability: 0,
        weeklyDownloads: '5.2M',
        age: '8 years',
        reason: 'Official Framework Core',
        threatDetails: 'Verified Vercel cryptographic provenance and signed releases.',
        suggestedAction: 'None required.'
      },
      {
        id: 'dep-5',
        name: 'zod',
        version: '^3.23.8',
        ecosystem: 'npm',
        riskLevel: 'SAFE',
        anomalyType: 'VERIFIED',
        registryExists: true,
        hallucinationProbability: 0,
        weeklyDownloads: '12.8M',
        age: '4 years',
        reason: 'Standard Schema Validator',
        threatDetails: 'High download velocity and verified Colin McDonnell maintainership.',
        suggestedAction: 'None required.'
      }
    ]
  },
  {
    id: 'pypi-data-science-typosquats',
    name: 'PyPI LLM Data Science Pipeline',
    ecosystem: 'pypi',
    filename: 'requirements.txt',
    description: 'Python requirements populated by AI agent with hallucinated GPU bindings and typosquats.',
    blastRadius: 88,
    rawContent: `numpy==1.26.4
pandas==2.2.2
scikit-learn-gpu==1.4.2
colourama==0.4.6
torchvision==0.18.0
request-http==2.31.0
tqdm==4.66.4`,
    dependencies: [
      {
        id: 'pypi-1',
        name: 'scikit-learn-gpu',
        version: '==1.4.2',
        ecosystem: 'pypi',
        riskLevel: 'CRITICAL',
        anomalyType: 'HALLUCINATED',
        registryExists: false,
        hallucinationProbability: 99,
        weeklyDownloads: '0',
        age: 'UNREGISTERED',
        reason: 'Fake Package (LLM Conflation)',
        threatDetails: 'LLM conflated scikit-learn with cuML/PyTorch GPU naming conventions. Name is unclaimed on PyPI.',
        suggestedAction: 'Register placeholder on PyPI or use cuml / scikit-learn natively.',
        claimCommand: 'flit publish --repository pypi'
      },
      {
        id: 'pypi-2',
        name: 'colourama',
        version: '==0.4.6',
        ecosystem: 'pypi',
        riskLevel: 'HIGH',
        anomalyType: 'TYPOSQUAT',
        registryExists: true,
        hallucinationProbability: 91,
        weeklyDownloads: '310',
        age: '5 days ago',
        reason: 'British-English Typosquat of colorama',
        threatDetails: 'Known typosquatting vector mimicking popular terminal color library colorama.',
        suggestedAction: 'Replace with colorama.'
      },
      {
        id: 'pypi-3',
        name: 'request-http',
        version: '==2.31.0',
        ecosystem: 'pypi',
        riskLevel: 'HIGH',
        anomalyType: 'TYPOSQUAT',
        registryExists: true,
        hallucinationProbability: 82,
        weeklyDownloads: '82',
        age: '1 week ago',
        reason: 'Typosquat of requests library',
        threatDetails: 'Shadow package attempting to intercept developers making singular/plural typos.',
        suggestedAction: 'Replace with requests.'
      },
      {
        id: 'pypi-4',
        name: 'pandas',
        version: '==2.2.2',
        ecosystem: 'pypi',
        riskLevel: 'SAFE',
        anomalyType: 'VERIFIED',
        registryExists: true,
        hallucinationProbability: 0,
        weeklyDownloads: '38M',
        age: '12 years',
        reason: 'Official PyData Distribution',
        threatDetails: 'Trusted scientific computing core.',
        suggestedAction: 'None required.'
      }
    ]
  },
  {
    id: 'malicious-lifecycle-hook',
    name: 'NPM Lifecycle Hook Poisoning Manifest',
    ecosystem: 'npm',
    filename: 'package.json',
    description: 'Dependency bundle containing packages with hidden postinstall payload extraction.',
    blastRadius: 96,
    rawContent: `{
  "name": "payment-microservice",
  "version": "2.4.0",
  "dependencies": {
    "express": "^4.19.2",
    "stripe": "^15.8.0",
    "npm-preinstall-fix": "^1.0.0",
    "dotenv": "^16.4.5"
  }
}`,
    dependencies: [
      {
        id: 'hook-1',
        name: 'npm-preinstall-fix',
        version: '^1.0.0',
        ecosystem: 'npm',
        riskLevel: 'CRITICAL',
        anomalyType: 'MALICIOUS_HOOK',
        registryExists: true,
        hallucinationProbability: 75,
        weeklyDownloads: '12',
        age: '12 hours ago',
        reason: 'Malicious Preinstall Hook Detected',
        threatDetails: 'Package contains "scripts": {"preinstall": "node -e \\"require(\'http\').get(...)`"} to exfiltrate AWS_SECRET_ACCESS_KEY from process.env.',
        suggestedAction: 'Block immediately via .npmrc ignore-scripts=true and remove from manifest.',
        claimCommand: 'npm uninstall npm-preinstall-fix'
      },
      {
        id: 'hook-2',
        name: 'express',
        version: '^4.19.2',
        ecosystem: 'npm',
        riskLevel: 'SAFE',
        anomalyType: 'VERIFIED',
        registryExists: true,
        hallucinationProbability: 0,
        weeklyDownloads: '32M',
        age: '14 years',
        reason: 'Core Web Framework',
        threatDetails: 'OpenJS Foundation cryptographic verification.',
        suggestedAction: 'None required.'
      }
    ]
  },
  {
    id: 'clean-enterprise-lockfile',
    name: 'Hardened Zero-Slop Enterprise Manifest',
    ecosystem: 'npm',
    filename: 'package.json',
    description: 'Vetted enterprise dependencies with 100% cryptographic registry pinning and 0 hallucinations.',
    blastRadius: 4,
    rawContent: `{
  "name": "core-banking-gateway",
  "version": "3.0.0",
  "dependencies": {
    "@fastify/cors": "^9.0.1",
    "fastify": "^4.27.0",
    "pg": "^8.11.5",
    "pino": "^9.1.0"
  }
}`,
    dependencies: [
      {
        id: 'clean-1',
        name: 'fastify',
        version: '^4.27.0',
        ecosystem: 'npm',
        riskLevel: 'SAFE',
        anomalyType: 'VERIFIED',
        registryExists: true,
        hallucinationProbability: 0,
        weeklyDownloads: '1.8M',
        age: '7 years',
        reason: 'Verified High-Performance Server',
        threatDetails: 'Rigorous OpenSSF scorecard rating: 9.2/10.',
        suggestedAction: 'None required.'
      },
      {
        id: 'clean-2',
        name: 'pino',
        version: '^9.1.0',
        ecosystem: 'npm',
        riskLevel: 'SAFE',
        anomalyType: 'VERIFIED',
        registryExists: true,
        hallucinationProbability: 0,
        weeklyDownloads: '6.4M',
        age: '8 years',
        reason: 'Signed Structured Logger',
        threatDetails: 'OpenSSF scorecard rating: 8.9/10.',
        suggestedAction: 'None required.'
      }
    ]
  }
];
